### ISSUE TITLE
What about a new release?

### ISSUE THREAD

**Issue by alonl** [jenkinsci/docker-jnlp-slave#30]
Hey guys,

First, thanks a lot for maintaining this repo.

Can you please consider releasing a new version? 

Now, when I want to use a version later than 2.62 of this Docker image, I have to use 'latest' - and it's very very not convenient...

Thanks,

**Comment by oleg-nenashev** [comment]
Well, it was quite intentional, `latest` branch is being automatically released.
I could add tags for the latest remoting 3.x release if it helps, but I suppose #31 needs to be fixed first

**Comment by alonl** [comment]
@oleg-nenashev I'm really waiting for that. :) But I think it must be on a regular basis...

**Comment by oleg-nenashev** [comment]
@alonl @carlossg @ndeloof @dduportal 

I have enabled tag autobuild on DockerHub. I propose the following versioning:

### https://github.com/jenkinsci/docker-slave/

We do not plan to ship multiple JDKs AFAIK (do we?), hence the approach could be straightforward. Additional version field is required, because we need to ship multiple image versions for a single 

 * Master: `${REMOTING_VERSION}-${INCREMENTAL_BUILD_ID}` 
 * Alpine:   `${REMOTING_VERSION}-${INCREMENTAL_BUILD_ID}-alpine`

### This repo

Same versioning approach, `INCREMENTAL_BUILD_ID` is independent from the the docker-slave's one:

 * Master: `${REMOTING_VERSION}-${INCREMENTAL_BUILD_ID}` 
 * Alpine:   `${REMOTING_VERSION}-${INCREMENTAL_BUILD_ID}-alpine`

WDYT? Is it enough or should we do something more complex?

**Comment by dduportal** [comment]
@oleg-nenashev At first glance, LGTM.

The question is : "If I still use the version tagged x-y or x-y-alpine in 6 month, will the behavior stay the same".
=> Your proposal makes sense as answer.

**Comment by carlossg** [comment]
I think multiple JDKs are going to be needed, we would like to try JDK9 soon-ish

**Comment by oleg-nenashev** [comment]
> I think multiple JDKs are going to be needed, we would like to try JDK9 soon-ish

Java 9 is gonna to be PITA. But I agree, this is a good point to have the jdk version included

**Comment by ndeloof** [comment]
We should use required Java version to run the slave agent (aka openjdk8), not try to cover all possible JDKs. People who want to build on other JDKs should just extend this image to pre-install it or use tool installers.

**Comment by oleg-nenashev** [comment]
Will start doing without JDK for now.
I think we will rename the images soon ([JENKINS-42846](https://issues.jenkins-ci.org/browse/JENKINS-42846)), so we can easily change the approach after it.

**Comment by oleg-nenashev** [comment]
I have created the `3.7-1` and `3.7-1-alpine` tags in both repositories, and they have been built and published correctly. 

Currently there is no explicit dependency between docker-jnlp-slave and docker-slave versions, which needs to be fixed IMHO (tag rebuild will pick the latest docker-slave, which may change). I am not sure how to implement it without changing the automatic publishing flow for `latest` and `alpine`. Maybe we need a Jenkinsfile and Multi-branch Pipeline. Then we will be able to replace DockerHub builder by Jenkins-on-Jenkins and also to sign the images.

**Comment by oleg-nenashev** [comment]
Nobody responded, so I assume it is fine

**Comment by dduportal** [comment]
Sorry @oleg-nenashev , missed your messages.

One interesting thing, with your flow, is that we can "fine-tune" our build & deploy process with your proposal, which is awesome.

However, I would propose that the "deploy" could be a webhook to the DockerHub that "triggers" the DockerHub build:

- This won't be a "binary reuse" since the image tested would have been the one in our CI/CD
- But this is a move in favor the "trust":
  * Trusting Docker ability to make things portable (consistant rebuild)
  * Letting user trust us as image provider, by reusing the Docker automatic build linking the image tags to the related Dockerfile, bringing a level of transparency that helps our user to learn, making easier any future contribution !

Here is a quick and dirty example with CircleCI (yeah I know, but I don't had at this time a free an maintained Jenkins instance ) that can be done easily within a Jenkinsfile: https://github.com/dduportal-dockerfiles/docker-compose/blob/master/circle.yml#L12

WDYT ?

**Comment by oleg-nenashev** [comment]
@dduportal Yes, I would like to have Jenkinsfile-powered builds on Jenkins-on-Jenkins instead of DockerHub. It would be much more convenient from the release management PoV and from Jenkins dogfooding. The only problem is to find some time for that
