### ISSUE TITLE
"checkout scm" on ssh secured private git repo not working on alpine (jenkinsci/jnlp-slave:alpine) due to missing ssh

### ISSUE THREAD

**Issue by TGippert** [jenkinsci/docker-jnlp-slave#34]
The ssh package (openssh?) seems to be missing in the alpine edition of the jnlp-slave (jenkinsci/jnlp-slave:alpine).
Thus I am not able to do a "checkout scm" from a private github repo secured by ssh access.

Error Message:  `stderr: /tmp/ssh2342644730406476600.sh: line 6: ssh: not found`

Current workaround: Use of jenkinsci/jnlp-slave instead of jenkinsci/jnlp-slave:alpine

See also: [https://issues.jenkins-ci.org/browse/JENKINS-41137](https://issues.jenkins-ci.org/browse/JENKINS-41137)

**Comment by oleg-nenashev** [comment]
Probably as designed, `alpine` is a minimal image for a reason. The main use-case for it is to use it as a base image and to install the stuff you need.

SSH is not required for the agent operation itself. If we want to include it, it needs more votes

**Comment by drywheat** [comment]
I also require SSH when using this alpine-based image in order to clone git repositories. Nevertheless, I agree with @oleg-nenashev, it makes more sense to use this image as a base for all of your needs `FROM jenkinsci/jnlp-slave:alpine`.

Thinks of the case where someone wants to use **https**, or some other protocol. Should this image include `curl` and/or `wget` as well? I think not.

**Comment by oleg-nenashev** [comment]
No response from @TGippert , so I suppose the only thing is to explain limitations/purpose of the Alpine image in the documentation

**Comment by TGippert** [comment]
Hello Oleg, excuse for the late response. 
I think, @drywheat wrote a good solution: Create an own image based on jnlp-slave:alpine.
This should work for us :-)
