### ISSUE TITLE
error while loading shared libraries: libapparmor.so.1

### ISSUE THREAD

**Issue by jsindy** [jenkinsci/docker-jnlp-slave#40]
Container-Optimized OS (cos) - GKE kubernetes 1.5.6 works fine
Container-Optimized OS (cos) - GKE kubernetes 1.6.6 fails with the following error.

docker: error while loading shared libraries: libapparmor.so.1: cannot open shared object file: No such file or directory

I don't see a way to open an issue with https://github.com/jenkinsci/kubernetes-plugin

Any help or guidance would be appreciated.

**Comment by oleg-nenashev** [comment]
@jsindy Regarding the Kubernetes plugin, see https://wiki.jenkins.io/display/JENKINS/How+to+report+an+issue

**Comment by james75** [comment]
Got the same error on 1.6.6.
Downgrading my cluster to - GKE kubernetes 1.6.4 fixed this issue.

**Comment by clanstyles** [comment]
I'm having the same issue. I'll try down grading and report back.

**Comment by ctavan** [comment]
Same issue here, works with 1.6.4, doesn't work with 1.6.6 on GKE. Has anybody reported this to Google yet?

**Comment by mhelmer** [comment]
I'm assuming you're seeing this when using docker in docker with `/usr/bin/docker` mounted as a Host Volume?

If that's the case, then the issue is that the mounted docker binary is linked against `libapparmor.so.1` which is not available in the container. You can solve it by mounting the shared libraries from the host as well, eg:

Host Path: `/usr/lib64/libapparmor.so.1.3.0`
Mount Path: `/lib/x86_64-linux-gnu/libapparmor.so.1`

Host Path: `/usr/lib64/libseccomp.so.2.3.1`
Mount Path: `/lib/x86_64-linux-gnu/libseccomp.so.2`

However, I think a better solution is to build a new image from your `jnlp` with a compatible version of docker installed, and then only use a host volume for the docker socket.

Anyway, it seems to be a configuration issue rather than an issue with jenkins, kubernetes or GKE.

Hope this helps!

**Comment by ctavan** [comment]
Thanks @mhelmer for the hint!

For the record: Upgrading my base image to `jenkinsci/jnlp-slave:3.10-1` (which brought the new `libapparmor.so.1`) and `apt-get install libseccomp2` in it solved the issue for me (without the need of mounting additional libraries into the slave container).
