### ISSUE TITLE
Create new release with fix for CVE-2018-17456

### ISSUE THREAD

**Issue by sameersbn** [jenkinsci/docker-jnlp-slave#71]
On Oct 5th, 2018 there has been a public disclosure of a Git security issue https://marc.info/?l=git&m=153875888916397&w=2. A new version of the alpine linux image has landed with the patched git version `1.18.1`. It would be really great if new releases of the `jenkins/jnlp-slave` and `jenkins/jenkins` images were released allowing users to patch these security vulnerabilities.

**Comment by oleg-nenashev** [comment]
All images have been respinned. Please verify

**Comment by oleg-nenashev** [comment]
Thanks for raising the flag about the issue @sameersbn! We definitely missed that announcement. In order to address the concern for Docker images, I have created https://issues.jenkins-ci.org/browse/INFRA-1832 as a follow-up (triggers for upstream component releases). 

Next time please use the https://jenkins.io/security/#reporting-vulnerabilities process next time if you see such issues. It will help us to react to the issues quickly and to coordinate releases if needed

**Comment by jeff-knurek** [comment]
@oleg-nenashev thanks for the deeper details about reporting such issues

I'd like to point out that I created an issue on the same topic over a month ago: 
https://github.com/jenkinsci/docker/issues/726
it got some attention, but clearly not enough

**Comment by sameersbn** [comment]
thanks for the quick turnaround @oleg-nenashev 
best regards.

**Comment by oleg-nenashev** [comment]
I have also rebuilt https://hub.docker.com/r/jenkins/ssh-slave/ (CC @ndeloof). I believe we are okay here for now
